webtalk_init -webtalk_dir D:/Projects/mine/PmodICSIF/FPGA/uart_primitive/uart_primitive.sim/sim_1/behav/xsim/xsim.dir/uart_tx_sim_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Thu Oct  3 19:49:57 2019" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2018.3.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2489853" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "174120556_177143225_210653087_704" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "914f7a57-35f1-4135-9c7f-dc3479036b2a" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "6a4bd667369a4300a8d17138fec8110e" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "10" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 7 , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Service Pack 1  (build 7601)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-4770K CPU @ 3.50GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3491 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "21.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "201 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "2" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.01_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "8892_KB" -context "xsim\\usage"
webtalk_transmit -clientid 3916367681 -regid "174120556_177143225_210653087_704" -xml D:/Projects/mine/PmodICSIF/FPGA/uart_primitive/uart_primitive.sim/sim_1/behav/xsim/xsim.dir/uart_tx_sim_behav/webtalk/usage_statistics_ext_xsim.xml -html D:/Projects/mine/PmodICSIF/FPGA/uart_primitive/uart_primitive.sim/sim_1/behav/xsim/xsim.dir/uart_tx_sim_behav/webtalk/usage_statistics_ext_xsim.html -wdm D:/Projects/mine/PmodICSIF/FPGA/uart_primitive/uart_primitive.sim/sim_1/behav/xsim/xsim.dir/uart_tx_sim_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
