webtalk_init -webtalk_dir C:/Projects/PmodICSIF/FPGA/icsuart0_core/icsuart0_core.sim/sim_1/behav/xsim/xsim.dir/icsuart0_core_sim_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Mon Oct 21 19:10:54 2019" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2018.3 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2405991" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "71d5170b-6f59-4f3a-be29-dc1994b02c1a" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "6a1a158603424fa790e4c029e6899b36" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "7" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-3537U CPU @ 2.00GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2494 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "101 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "3" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.14_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "7108_KB" -context "xsim\\usage"
webtalk_transmit -clientid 2970296833 -regid "" -xml C:/Projects/PmodICSIF/FPGA/icsuart0_core/icsuart0_core.sim/sim_1/behav/xsim/xsim.dir/icsuart0_core_sim_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Projects/PmodICSIF/FPGA/icsuart0_core/icsuart0_core.sim/sim_1/behav/xsim/xsim.dir/icsuart0_core_sim_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Projects/PmodICSIF/FPGA/icsuart0_core/icsuart0_core.sim/sim_1/behav/xsim/xsim.dir/icsuart0_core_sim_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
